-- MySQL Script generated by MySQL Workbench
-- 12/10/17 00:33:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema USISCOM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema USISCOM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `USISCOM` DEFAULT CHARACTER SET utf8 ;
USE `USISCOM` ;

-- -----------------------------------------------------
-- Table `USISCOM`.`Artículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USISCOM`.`Artículo` (
  `idArtículo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Descripción` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Precio` DOUBLE NULL DEFAULT NULL COMMENT '',
  `Unidades` INT NULL DEFAULT NULL COMMENT '',
  `Imagen` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idArtículo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USISCOM`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USISCOM`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre_cliente` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Institucion_cliente` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha` DATE NULL DEFAULT NULL COMMENT '',
  `Costo` DOUBLE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idPedido`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USISCOM`.`Pedido_Artículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USISCOM`.`Pedido_Artículo` (
  `idArtículo` INT NOT NULL COMMENT '',
  `idPedido` INT NOT NULL COMMENT '',
  `Cantidad` DOUBLE NULL DEFAULT NULL COMMENT '',
  INDEX `idPedido_idx` (`idPedido` ASC)  COMMENT '',
  INDEX `idArtículo` (`idArtículo` ASC)  COMMENT '',
  CONSTRAINT `idArtículo`
    FOREIGN KEY (`idArtículo`)
    REFERENCES `USISCOM`.`Artículo` (`idArtículo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `USISCOM`.`Pedido` (`idPedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USISCOM`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USISCOM`.`Venta` (
  `idVenta` INT NOT NULL COMMENT '',
  `Fecha_inicio` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_fin` DATE NULL DEFAULT NULL COMMENT '',
  `Repartidor` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Estatus` INT NULL DEFAULT NULL COMMENT '',
  `idPedido` INT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idVenta`)  COMMENT '',
  INDEX `idPedido_idx` (`idPedido` ASC)  COMMENT '',
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `USISCOM`.`Pedido` (`idPedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
